version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    machine: true
    steps:
      - run: git clone https://github.com/aimmori/Labo2CircleCIBackend.git 
      - run: npm install 
      - run: npm test

  integrationFrontend:
    machine: true
    steps:
      - run: git clone https://github.com/aimmori/Labo2CircleCiFrontend.git
      - run: npm install 
      - run: npm run build 
      - run: mkdir -p ../3w5-h24-tp2-backend/public 
      - run: cp -rT build ../3w5-h24-tp2-backend/public

      - persist_to_workspace:
          root: 3w5-h24-tp2-backend/public
          paths:
            - .
      - attach_workspace:
          at: .
  deploiement:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cd 3w5-h24-tp2-backend 
      - run: ls -Rl
workflows:
  monWorkflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
