version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    executor:
      name: node/default
    steps:
      - run:
          name: Checkout code
          command: git clone https://github.com/aimmori/Labo2CircleCIBackend.git 
      - run:
          name: Install dependencies
          command: |
            cd Labo2CircleCIBackend
            npm install
      - run:
          name: Run tests
          command: |
            cd Labo2CircleCIBackend
            npm run test


  integrationFrontend:
    machine: true
    steps:
      - run: 
          name: Checkout code
          command: git clone https://github.com/aimmori/Labo2CircleCiFrontend.git 
      - run:
            name: Install dependencies
            command: |
             cd Labo2CircleCiFrontend
             npm install 
      - run: 
            name: Install Build 
            command: |
              cd Labo2CircleCiFrontend
              npm run build 
      - run: 
            name: Créer dossier public
            command: mkdir -p Labo2CircleCIBackend/public 
      - run: 
            name: Copier le build dans public
            command: cp -r Labo2CircleCiFrontend/build/ Labo2CircleCIBackend/public/

      - persist_to_workspace:
          root: Labo2CircleCIBackend/public
          paths:
            - .
      - attach_workspace:
          at: .
  deploiement:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cd .
      - run: ls -Rl
workflows:
  monWorkflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
