version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/aimmori/Labo2CircleCIBackend.git 
      - run: cd Labo2CircleCIBackend && npm install
      - run: chmod +x Labo2CircleCIBackend/node_modules/.bin/jest
      - run: cd Labo2CircleCIBackend && jest


  integrationFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: 
          name: Checkout code
          command: git clone https://github.com/aimmori/Labo2CircleCiFrontend.git 
      - run:
            name: Install dependencies
            command: |
             cd Labo2CircleCiFrontend
             npm install 
      - run: 
            name: Install Build 
            command: |
              cd Labo2CircleCiFrontend
              npm run build 
      - run: 
            name: Créer dossier public
            command: mkdir -p Labo2CircleCIBackend/public 
      - run: 
            name: Copier le build dans public
            command: cp -r Labo2CircleCiFrontend/build/ Labo2CircleCIBackend/public/

      - persist_to_workspace:
          root: Labo2CircleCIBackend/public
          paths:
            - .
      - attach_workspace:
          at: .
  deploiement:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - attach_workspace:
          at: .
      - run: cd .
      - run: ls -Rl
workflows:
  monWorkflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
