version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    executor:
      name: node/default
    steps:
      - run:
          name: Checkout code
          command: git clone https://github.com/aimmori/Labo2CircleCIBackend.git backend
      - run:
          name: Install dependencies
          command: |
            cd backend
            npm install
      #- run:
       #   name: Run tests
        #  command: |
         #   cd backend
          #  npm run test


  integrationFrontend:
    machine: true
    steps:
      - run: 
          name: Checkout code
          command: git clone https://github.com/aimmori/Labo2CircleCiFrontend.git frontend
      - run:
            name: Install dependencies
            command: |
             cd frontend
             npm install 
      - run: 
            name: Install Build 
            command: |
              cd frontend
              npm run build 
      - run: 
            name: Créer dossier public
            command: mkdir -p backend/public 
      - run: 
            name: Copier le build dans public
            command: cp -r frontend/build/ backend/public/

      - persist_to_workspace:
          root: backend/public
          paths:
            - .
      - attach_workspace:
          at: .
  deploiement:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cd .
      - run: ls -Rl
workflows:
  monWorkflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
